DROP TABLE INVENTORY_CONSUMER CASCADE CONSTRAINTS;
SET sqlblanklines on;

CREATE TABLE INVENTORY_CONSUMER(

      orderID INT NOT NULL,
      type VARCHAR(50) NOT NULL,
      qty INT NOT NULL       
);