DROP TABLE EX_ORDERS CASCADE CONSTRAINTS;
DROP TABLE FN_ORDERS CASCADE CONSTRAINTS;

SET sqlblanklines on;

CREATE TABLE  EX_ORDERS(
   name	VARCHAR(20) NOT NULL,
   part_id INT NOT NULL,
   quantity INT NOT NULL,
   buyer VARCHAR(20) NOT NULL
   
);

CREATE TABLE  FN_ORDERS(
   name VARCHAR(20) NOT NULL,
   part_id INT NOT NULL,
   quantity INT NOT NULL,
   buyer VARCHAR(20) NOT NULL
   
);

 